// MIT. Pure Node DOM/data-contract test; no browser, navigation, network or scientific execution.
import fs from 'node:fs';import vm from 'node:vm';import assert from 'node:assert/strict';
const root=process.argv[2];const data=JSON.parse(fs.readFileSync(root+'/docs/power-progress/data.json','utf8'));
class Element{constructor(tag='div'){this.tagName=tag;this.children=[];this.attributes={};this.textContent='';this.value='';this.checked=false;}append(...items){this.children.push(...items);}replaceChildren(...items){this.children=items;}setAttribute(k,v){this.attributes[k]=v;}click(){if(this.onclick)this.onclick();}}
const nodes=new Map(),defaults={'metric-select':'average_net_MW','world-series':'nif-energy'};function get(id){if(!nodes.has(id)){const e=new Element();e.value=defaults[id]??'';nodes.set(id,e);}return nodes.get(id);}
const errors=[],downloads=[];const mockURL={createObjectURL:b=>{downloads.push(b);return'blob:test';},revokeObjectURL:()=>{}};
const context=vm.createContext({document:{getElementById:get,createElement:t=>new Element(t),createElementNS:(_n,t)=>new Element(t)},fetch:async url=>{assert.equal(url,'data.json');return{ok:true,json:async()=>data};},console:{error:x=>errors.push(String(x))},URL:mockURL,Blob,setTimeout:()=>0});
vm.runInContext(fs.readFileSync(root+'/docs/power-progress/view.js','utf8'),context,{timeout:10000});await new Promise(r=>setImmediate(r));await new Promise(r=>setImmediate(r));assert.deepEqual(errors,[]);
assert.equal(get('best-average').textContent,'274.0');assert.equal(get('physical-output').textContent,'Not measured');assert.equal(get('history-table').children.length,12);assert.equal(get('world-table').children.length,11);
function flatten(e){return[e,...e.children.flatMap(flatten)];}function text(e){return[e.textContent,...e.children.map(text)].join(' ');}function finite(e){for(const [k,v]of Object.entries(e.attributes))if(['points','x','y','x1','x2','y1','y2','cx','cy'].includes(k))assert.ok(!/NaN|Infinity|undefined/.test(v),v);e.children.forEach(finite);}
for(const metric of ['average_net_MW','flat_top_net_MW'])for(const include of [false,true]){get('metric-select').value=metric;get('show-excluded').checked=include;get('metric-select').onchange();finite(get('history-chart'));const points=flatten(get('history-chart')).filter(e=>e.attributes['data-history']);assert.equal(points.length,data.history.filter(r=>r[metric]!==null&&(include||r.eligible_for_model_best)).length);for(const point of points){point.click();assert.ok(text(get('history-detail')).includes('MW'));}}
get('metric-select').value='average_net_MW';get('show-excluded').checked=true;get('show-excluded').onchange();const retired=flatten(get('history-chart')).find(e=>e.attributes['data-history']==='retired-screen');retired.click();assert.match(text(get('history-detail')),/Excluded/);assert.equal(get('best-average').textContent,'274.0');
for(const mode of ['nif-energy','jet-energy','tokamak-peak']){get('world-series').value=mode;get('world-series').onchange();finite(get('world-chart'));for(const p of flatten(get('world-chart')).filter(e=>e.attributes['data-world'])){p.click();assert.match(text(get('world-detail')),/NOT NET ELECTRICITY/);}}
get('world-series').value='jet-energy';get('world-series').onchange();const jet=flatten(get('world-chart')).find(e=>e.attributes['data-world']==='jet-2023-energy');jet.click();assert.match(text(get('world-detail')),/13\.269/);assert.match(text(get('world-detail')),/13\.800/);
get('export-history').click();assert.equal(downloads.length,1);const csv=await downloads[0].text();assert.equal(csv.split('\r\n').length,13);assert.match(csv,/406.53/);assert.match(csv,/steady200/);
const homepage=vm.createContext({document:{getElementById:get},fetch:async url=>{assert.equal(url,'./power-progress/data.json');return{ok:true,json:async()=>data};}});vm.runInContext(fs.readFileSync(root+'/tools/pages/power-summary.js','utf8'),homepage);await new Promise(r=>setImmediate(r));await new Promise(r=>setImmediate(r));assert.equal(get('power-summary-best').textContent,'274.0 MW');assert.equal(get('power-summary-reference').textContent,'213.7 MW');assert.deepEqual(errors,[]);
console.log(JSON.stringify({passed:true,history_records:12,physical_milestones:11,history_modes_tested:4,measurement_modes_tested:3,csv_export_checked:true,homepage_summary_checked:true,browser_rendering_verified:false,scope:'Node DOM contract only; not browser rendering or accessibility audit',network_requests:0,scientific_runs:0}));
