// Original MIT. Actual OpenMC states and voxel means; display markers are not physical sizes.
import * as THREE from 'three';
import {OrbitControls} from 'three/addons/controls/OrbitControls.js';
const $=id=>document.getElementById(id);let data=null,current=null,group=null,particles=null,field=null,paths=[],timeMax=1e-6,phase=.4,playing=true;
const scene=new THREE.Scene();scene.background=new THREE.Color('#07121c');const camera=new THREE.PerspectiveCamera(45,1,.1,5000);camera.up.set(0,0,1);camera.position.set(-430,-330,240);
const renderer=new THREE.WebGLRenderer({antialias:true});renderer.setPixelRatio(Math.min(devicePixelRatio,2));$('transport-viewport').append(renderer.domElement);const controls=new OrbitControls(camera,renderer.domElement);controls.enableDamping=true;
scene.add(new THREE.HemisphereLight(0xaacfff,0x292516,2));const light=new THREE.DirectionalLight(0xffefde,4);light.position.set(-200,-300,600);scene.add(light);
const metal=new THREE.MeshStandardMaterial({color:0x8296a7,metalness:.5,roughness:.3,side:THREE.DoubleSide});const ghost=new THREE.MeshBasicMaterial({color:0xc1a26b,transparent:true,opacity:.055,side:THREE.DoubleSide,depthWrite:false});const helium=new THREE.MeshBasicMaterial({color:0x246bb9,transparent:true,opacity:.14,side:THREE.DoubleSide,depthWrite:false});
const color=v=>{const a=new THREE.Color(.025,.07,.25),b=new THREE.Color(.04,.82,.68),c=new THREE.Color(1,.38,.07);return v<.5?a.lerp(b,2*v):b.lerp(c,2*v-1);};
const position=p=>new THREE.Vector3(p[0]-data.dimensions_cm[0]/2,p[1]-data.dimensions_cm[1]/2,p[2]-data.dimensions_cm[2]/2);
function box(lo,hi,mat){const s=hi.map((v,i)=>v-lo[i]),m=new THREE.Mesh(new THREE.BoxGeometry(...s),mat);m.position.copy(position(lo.map((v,i)=>(v+hi[i])/2)));group.add(m);return m;}
function cylinder(r,h,x,y,z,mat,cut=false){const m=new THREE.Mesh(new THREE.CylinderGeometry(r,r,h,64,1,cut,cut?Math.PI*.15:0,cut?Math.PI*1.5:Math.PI*2),mat);m.rotation.x=Math.PI/2;m.position.copy(position([x,y,z]));group.add(m);return m;}
function clear(){if(group){group.traverse(o=>{if(o.geometry)o.geometry.dispose();});scene.remove(group);}group=new THREE.Group();scene.add(group);}
function makeField(){if(field){group.remove(field);field.geometry.dispose();}const [sx,sy,sz]=data.dimensions_cm,z=Math.min(15,Number($('transport-slice').value));const vertices=[],colors=[];const level=(z+.5)*sz/16;
 for(let y=0;y<16;y++)for(let x=0;x<24;x++){const i=x+24*(y+16*z),v=current.heating_density[i],se=current.heating_standard_error_density[i],known=v>0&&se/v<=.5,c=known?color(Math.log1p(v)/Math.log1p(data.common_heating_scale)):new THREE.Color(.13,.13,.16);const q=[[x*sx/24,y*sy/16,level],[(x+1)*sx/24,y*sy/16,level],[(x+1)*sx/24,(y+1)*sy/16,level],[x*sx/24,(y+1)*sy/16,level]];for(const k of [0,1,2,0,2,3]){vertices.push(...position(q[k]).toArray());colors.push(c.r,c.g,c.b);}}
 const g=new THREE.BufferGeometry();g.setAttribute('position',new THREE.Float32BufferAttribute(vertices,3));g.setAttribute('color',new THREE.Float32BufferAttribute(colors,3));field=new THREE.Mesh(g,new THREE.MeshBasicMaterial({vertexColors:true,side:THREE.DoubleSide}));field.visible=$('transport-field').checked;group.add(field);}
function select(index){if(!data)return;current=data.cases[index];clear();const [sx,sy,sz]=data.dimensions_cm,cut=$('transport-cutaway').checked;box([0,0,0],[sx,sy,sz],ghost);const edges=new THREE.LineSegments(new THREE.EdgesGeometry(new THREE.BoxGeometry(sx,sy,sz)),new THREE.LineBasicMaterial({color:0x28858e}));group.add(edges);
 box([-2.3,0,0],[-1.8,sy,cut?sz*.28:sz],metal);box([-1.8,0,0],[0,sy,cut?sz*.28:sz],metal);const ro=data.header_outer_radius_cm,ri=data.header_inner_radius_cm,cap=data.header_cap_cm,xx=current.layout==='headers_front'?ro:sx-ro;
 for(const yy of [sy/6,sy/2,5*sy/6]){cylinder(ro,sz,xx,yy,sz/2,metal,cut);cylinder(ri,sz-2*cap,xx,yy,sz/2,helium);for(const zz of [cap/2,sz-cap/2])cylinder(ro,cap,xx,yy,zz,metal);}
 paths=current.paths;timeMax=current.max_track_time_s;const pts=[],cs=[];for(const p of paths){const c=new THREE.Color(p.particle==='photon'?0xb67c16:0x13859b);for(let i=1;i<p.states.length;i++){pts.push(...position(p.states[i-1]).toArray(),...position(p.states[i]).toArray());cs.push(c.r,c.g,c.b,c.r,c.g,c.b);}}
 const tg=new THREE.BufferGeometry();tg.setAttribute('position',new THREE.Float32BufferAttribute(pts,3));tg.setAttribute('color',new THREE.Float32BufferAttribute(cs,3));const trail=new THREE.LineSegments(tg,new THREE.LineBasicMaterial({vertexColors:true,transparent:true,opacity:.55}));trail.name='recorded-trails';trail.visible=$('transport-trails').checked;group.add(trail);
 particles=new THREE.InstancedMesh(new THREE.SphereGeometry(.75,8,6),new THREE.MeshBasicMaterial({color:0xffffff}),paths.length);for(let i=0;i<paths.length;i++)particles.setColorAt(i,new THREE.Color(paths[i].particle==='photon'?0xffbd22:0x30efff));group.add(particles);makeField();
 $('transport-title').textContent=current.title;$('transport-numbers').textContent=`${current.source_histories.toLocaleString()} tally histories | ${paths.length} recorded paths from first 16 source histories\nTritons/source ${current.tritons_per_source.toFixed(5)} ± ${current.tritons_standard_error.toFixed(5)}; heating ${current.heating_MeV_per_source.toFixed(3)} MeV/source\nField: eV/cm³/source, common logarithmic scale 0–${data.common_heating_scale.toPrecision(4)}. Grey: statistical error >50% / no score.`;}
let pendingGuidedPlayback=false;
function guidedPlayback(){if(!data){pendingGuidedPlayback=true;return;}pendingGuidedPlayback=false;$('transport-case').value='4';$('transport-cutaway').checked=true;$('transport-trails').checked=true;$('transport-field').checked=false;phase=.08;playing=!matchMedia('(prefers-reduced-motion: reduce)').matches;$('transport-play').textContent=playing?'Pause':'Play';select(4);camera.position.set(-280,-215,156);controls.target.set(0,0,0);controls.update();unit.setScalar(1.8);group.getObjectByName('recorded-trails').material.opacity=.75;$('transport-viewport').dataset.view='calculated-reference-particles';}
window.addEventListener('workbench:watch-particles',guidedPlayback);
const matrix=new THREE.Matrix4(),zero=new THREE.Vector3(),unit=new THREE.Vector3(1,1,1),rotation=new THREE.Quaternion();let last=performance.now();
function animate(now){const dt=Math.min(.1,(now-last)/1000);last=now;if(data&&current&&$('transport').classList.contains('active')){if(playing)phase=(phase+dt/16)%1;const t=Math.expm1(Math.log1p(timeMax/1e-9)*phase)*1e-9;let visible=0;
 for(let i=0;i<paths.length;i++){const p=paths[i].states;let show=t>=p[0][3]&&t<=p.at(-1)[3],pos=zero;if(show){let lo=0,hi=p.length-1;while(hi-lo>1){const mid=(hi+lo)>>1;if(p[mid][3]<=t)lo=mid;else hi=mid;}const span=p[hi][3]-p[lo][3],u=span>0?(t-p[lo][3])/span:0;pos=position(p[lo]).lerp(position(p[hi]),u);visible++;}matrix.compose(pos,rotation,show?unit:zero);particles.setMatrixAt(i,matrix);}particles.instanceMatrix.needsUpdate=true;particles.frustumCulled=false;
 $('transport-time').value=String(Math.round(phase*1000));$('transport-clock').textContent=`${(t*1e6).toPrecision(4)} microseconds | ${visible} visible markers | logarithmic time. Independent histories are aligned at emission, not a real source pulse.`;
 $('transport-plain-clock').textContent=`${playing?'Playing recorded paths':'Paused'}  /  ${visible} visible markers  /  slow motion, not live fusion`; $('transport-viewport').dataset.recordedCase=current.id;
 controls.update();renderer.render(scene,camera);}requestAnimationFrame(animate);}requestAnimationFrame(animate);
new ResizeObserver(()=>{const r=$('transport-viewport').getBoundingClientRect();if(r.width&&r.height){renderer.setSize(r.width,r.height);camera.aspect=r.width/r.height;camera.updateProjectionMatrix();}}).observe($('transport-viewport'));
$('transport-case').onchange=()=>select(Number($('transport-case').value));$('transport-slice').oninput=()=>{if(data)makeField();};$('transport-cutaway').onchange=()=>select(Number($('transport-case').value));$('transport-field').onchange=()=>{if(field)field.visible=$('transport-field').checked;};$('transport-trails').onchange=()=>{if(group)group.getObjectByName('recorded-trails').visible=$('transport-trails').checked;};
$('transport-play').onclick=()=>{playing=!playing;$('transport-play').textContent=playing?'Pause':'Play';};$('transport-time').oninput=()=>{phase=Number($('transport-time').value)/1000;playing=false;$('transport-play').textContent='Play';};
renderer.domElement.addEventListener('click',e=>{if(!field?.visible)return;const r=renderer.domElement.getBoundingClientRect(),ray=new THREE.Raycaster();ray.setFromCamera(new THREE.Vector2(2*(e.clientX-r.left)/r.width-1,1-2*(e.clientY-r.top)/r.height),camera);const hit=ray.intersectObject(field)[0];if(!hit)return;const i=Math.floor(hit.faceIndex/2),z=Number($('transport-slice').value),k=i+384*z,v=current.heating_density[k],se=current.heating_standard_error_density[k];$('transport-probe').textContent=`Voxel (${i%24},${Math.floor(i/24)},${z}): ${v.toPrecision(5)} ± ${se.toPrecision(3)} eV/cm³/source; relative statistical error ${v>0?(100*se/v).toFixed(1):'unknown'}%.`+(current.incident_neutrons_s ? ` Conditional DT-rate scaling: ${(v*current.incident_neutrons_s*1.602176634e-19).toFixed(4)} MW/mÂ³; not experimentally validated.`:'');});
fetch('/api/transportlab').then(r=>{if(!r.ok)throw Error();return r.json();}).then(d=>{if(d.schema!=='fusion.transport-lab.v1'||d.cases.length!==6||d.physical_validation!==false)throw Error();data=d;select(0);if(pendingGuidedPlayback)guidedPlayback();}).catch(()=>{$('transport-title').textContent='Checked transport dataset unavailable';});
